### ISSUE TITLE
Save Wallet Password to config.json

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#108]
Have this as an option and warn users before they enable it that this is equivalent to decrypting their wallet constantly.

**Comment by pmknutsen** [comment]
Definitely convenient but saving the wallet seed in clear text to the file system is potentially irreversible due to file being copied through automated backups, deep file recovery scans etc. The wallet seed is very long and hard to memorize. Another option could be to save the wallet seed encrypted in config.json with a user-defined password. Thus, the default is a near-impossible password with the option of setting a second-level memorizable password in the UI. This would avoid saving the seed in clear-text.

**Comment by Mingling94** [comment]
Ohhh, creative idea! I'd have to do some research into how to use encryption though haha

**Comment by DavidVorick** [comment]
Let's do things one at a time. If a user wants to save their password, let's start with that. We can add a 'easier password' or something later on down the line.

For the record, the daemon already supports using custom passwords at wallet initialization.

**Comment by Mingling94** [comment]
I guess we should give that custom password option in the UI, probably after showing the suggested one. Also is there any `reset password` option?

**Comment by DavidVorick** [comment]
There is no `reset password` option, and you can't show the suggested one unless you opt to use it. There are very strong reasons not to use custom passwords in the daemon - if someone makes a rainbow table and finds your weak password address on the blockchain they can take your coins without ever accessing your computer. That's substantially less secure than having the password on disk b/c at least when it's on disk the attacker needs to access your computer and recognize the file as something worthwhile.

**Comment by Mingling94** [comment]
Alright. The above seems a reasonable argument for why saving the password in plaintext is more secure than the custom password.

**Comment by Mingling94** [comment]
Fixed via #114 and improved upon in #118
