### ISSUE TITLE
Incorrect Version Numbers

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#117]
In the Sia-UI, in the 'About' view, I have Sia UI version: 0.2.0 b313, and no version at all for Siad.

**Comment by lukechampine** [comment]
bumped the Sia UI version in ec71d62275e256f650.

I believe you aren't seeing a version for siad because you don't have internet. The version is pulled from the update call rather than a version call, so it needs to ping the linode to get the version. This will be fixed when we add a version API call to siad.
