### ISSUE TITLE
Default siac location

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#263]
The Terminal plugin should be able to automatically locate siac in most cases; it should be right next to siad. Instead, it seems to prompt the user for the location every time.

**Comment by droghio** [comment]
The issue stems from something nasty with the config saving. The Terminal plugin stores the location of siac in the config. The plugin does set the config correctly and it does update but when electron closes it resets the config file to an old version. @johnathanhowell believes this may be due to race conditions in the config manager.
