### ISSUE TITLE
Siad.exe only seem to use one CPU core therefore it's very slow to sync/start. Also, high memroy usage.

### ISSUE THREAD

**Issue by bathrobehero** [NebulousLabs/Sia-UI#300]
The CPU usage of siad.exe always seem to top out at 25% on a quadcore CPU so it only ever uses one core. It takes 3-5 minutes to start the wallet on a quadcore i3 CPU.

It should use all cores to work faster.

It also uses too much memory (~2GB) probably putting the whole consensus.db into the memory. Over time memory usage decreases to ~600 MB though.

**Comment by lukechampine** [comment]
Currently, wallet unlocking is an inherently serial process; it has to process each block in sequence. I'm not sure whether this can be optimized. @DavidVorick is working on a smarter wallet that will be able to unlock instantly, though. 
Rest assured that most of our code is making good use of multicore processors, thanks to Go's lightweight threads. For example, each peer connection has its own thread.

The high memory usage is likely due to [our database](https://github.com/boltdb/bolt), which mmap's its db file. I'm not 100% clear on the semantics of mmap though.

**Comment by DavidVorick** [comment]
My limited understanding is that the database is actually not using that much memory. For example, if you use `--modules cg` it should stay under 250MB of RAM. It should even stay under 250MB of RAM with `--modules cge`, despite the explorer having a much larger database than the consensus set.

I think that most of the memory usage right now is coming from `ProcessConsensusChange`, somehow related to the wallet, host, and renter.

There are several parts of the code where CPU parallelization would likely bring a lot of benefits. For example most of the cryptography in the consensus set is done in serial on a single core, but a lot of the hashing and signature verification could be done in parallel per-txn.

**Comment by droghio** [comment]
Closing since issue has been moved to the Sia issue tracker.
