### ISSUE TITLE
Wallet Plugin - Readable Siacoin Amounts

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#432]
I have a couple of transactions in my wallet plugin that display numbers like 

150000 SC

And that's pretty hard to read, especially at a distance (on, uh, the projector).

Would be better to switch to the standard sia units, e.g.

150 KS

5 MS

etc.

**Comment by Fornax96** [comment]
You could also add thousands separators. It's a bit annoying to get it working correctly on every locale since half the world uses commas and the other half uses dots. So I usually just use spaces in my applications, though that looks weird with monospace fonts :(. 

Here's a handy reference list in case you choose to use locale-specific separators: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

EDIT: Actually, there are more standards. This list is more complete: http://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-digits.html

Have a look at this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by pmknutsen** [comment]
`Number.toLocaleString()` should work.

**Comment by avahowell** [comment]
I'm definitely in favor of having readable SC units, similarly to how we have readable filesize units; if the quantity is over 1000, step up a unit size (2000SC becomes 2 KS, 5000000SC becomes 5 MS, etc, as david suggested).

**Comment by pmknutsen** [comment]
@johnathanhowell I would reconsider. Most numbers aren't that pretty. More likely, you have 57182SC which by your re-unit'ing scheme becomes 57.182 KS. You then assume users are really on top of their units, or they will misread the comma/period as thousand separator rather than decimals. Its a lot easier for users, I think, if the unit is the same all throughout the column and add (localized) thousand separators as @Fornax96 suggests instead. Changing the unit every row _will_ confuse.

**Comment by nebulousmediacenter** [comment]
perhaps adding commas then is better, I agree it would definitely be confusing to have multiple different denominations of currency in the same list of transactions.
