### ISSUE TITLE
Wallet stuck unlocking after rescan

### ISSUE THREAD

**Issue by buvs** [NebulousLabs/Sia-UI#605]
Hi,

Because my coins from a recent transaction were not appearing, I followed the steps at #581 in order to get them to show up in my wallet. However, after about 4 hours, my wallet still shows as unlocking. The command I ran to do the recovery was "recover-windows.exe set 1". Is this long of a wait to unlock my wallet expected?

As an aside, I'm not able to use the explorer to locate my transaction. The wallet address used was 7c3dd868990c4c32bbd8710fc61d66536b444b9b8ecf7e162eae5295e9973be01a795724ecd7.

Any help would be appreciated!

**Comment by avahowell** [comment]
It depends on the configuration of your system but 4 hours is not unheard of for a relatively slow system, especially one without an SSD. There are a number of performance improvements that are set to be released imminently that should bring the first-time unlock time down. Note that after you unlock for the first time, the wallet will only need to rescan blocks that have occured since the last time you unlocked, meaning subsequent unlocks will be much faster.

Your transaction might still be unconfirmed, try waiting a bit longer and it should show up.

**Comment by buvs** [comment]
So I'm guessing when after running the recover tool it told me it had to rescan from block 1, it meant that has to go through the entire blockchain again? Makes sense then that it's taking a while. Thanks for the info and the quick response!

2 more questions:

1. Is there any way to verify that that wallet address is valid and associated with my wallet seed (while my wallet is unlocking again)?

2. Is it safe to transact using the wallet address from above while my wallet is unlocking (since it's an old one and a new one is generated for each transaction)?

EDIT: Just wanted to add that it's been 8 hours now and my wallet still hasn't unlocked. Is it time to start troubleshooting?
