### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by powerpaul17** [NebulousLabs/Sia-UI#672]
Are there plans for a browser version of the GUI, since it's already a web application? Would be very useful for headless installations.

**Comment by lukechampine** [comment]
We did have a browser version initially, but scrapped for security reasons. Specifically, we didn't want an attacker to be able to steal coins by sending a malicious link like `localhost:9980/wallet/sendsiacoins?addr=attackerAddress`. That's why the API requires a special `User-Agent` string; browsers don't allow requests to change that string.

Another problem was that the UI needs access to the local file system because it needs to pass the full path of files on disk to the daemon.

If there are solutions to both of these problems, it's something that we'd consider.

**Comment by powerpaul17** [comment]
I see, that seems to be a reasonable explanation. Thank you for your quick reply.
