### ISSUE TITLE
Feature Proposal:  Integration with major exchanges to automatically renew siacoins

### ISSUE THREAD

**Issue by exit99** [NebulousLabs/Sia-UI#735]
**Problem**
Buying and transferring siacoin for contracts is a hassle.  This hassle prevents greater adoption.
Particularly, when a contract is close to expiration, there is too much diligence needed to ensure adequate levels of SIA

**Proposed Solution**
Allow the user to input an exchange API key to make purchases and transfers to their wallet when their total passes a specified threshold.

Initial supported exchanges:
Bittrex & Poloniex

I will tackle this if approved by maintainers.

**Comment by DavidVorick** [comment]
This unfortunately cannot be merged into a Nebulous Labs repo, because we do not support extending the UI with trusted features. Exchanges are a point of trust + centralization, and so first party apps are not allowed to integrate with them.

However, we fully support a third party making a plugin (in a non-Nebulous Labs repo) that can be distributed to the community. We can help you navigate the plugin system if you are interested in going that route, and would be happy to help you work with the API.

I hope this makes sense - I like your idea and think it would be valuable to the community, it just can't be added to a Nebulous Labs repo due to it's dependence on a centralized platform (the exchange).

**Comment by tbenz9** [comment]
@Kazanz I'd recommend you join the Sia Discord server if you're going to build a plugin; you will get real time help and advice there.  I believe the Devs will close this issue because in it's current form it will never be merged into the repo (it's still a great idea though).

Recommendation to devs: close
